services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: example_123
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/data

volumes:
  mssql-data:
